### PR TITLE
new feature

### PR DESCRIPTION
**Pull request by VarduhiG**

### CODE REVIEW

**Comment by sbayadya** [comment]
Everything is good Varduhi jan, the code is working properly, the structure is also good.

**Comment by VarduhiG** [comment]
Thanks!

**Comment by IgDMakarov** [comment]
Varduhi-jan, it good working. Just maybe one advice that is good idea to use check that format of input is right and ask user input value as many times as he'll try to input incorrect value.
image
and to my mind maybe checking minutes and seconds in input, because as we know in one hour is no more then 60 minutes and in one minute is no more then 60 seconds
But by the way your calculation works good and resolve this issue.

**Comment by VarduhiG** [comment]
Thanks

**Pull request merged**
